# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstacle',
            old_name='lon',
            new_name='long',
        ),
        migrations.RenameField(
            model_name='obstacle',
            old_name='type',
            new_name='type_desc',
        ),
        migrations.AddField(
            model_name='obstacle',
            name='mark_indicator',
            field=models.CharField(choices=[('P', 'Orange or Orange and White Paint'), ('W', 'White Paint Only'), ('M', 'Marked'), ('F', 'Flag Marker'), ('S', 'Spherical Marker'), ('N', 'None'), ('U', 'Unknown')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='action_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='horizontal_accuracy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='vertical_accuracy',
            field=models.FloatField(),
        ),
    ]
