# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0004_auto_20170311_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('iata', models.CharField(max_length=3, null=True)),
                ('icao', models.CharField(max_length=4, null=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('altitude', models.IntegerField()),
            ],
        ),
    ]
