# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0006_auto_20170311_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='long',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='long',
            field=models.FloatField(db_index=True),
        ),
    ]
