# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dof', '0008_auto_20170316_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='obstacle',
            name='location',
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
